x-veld:
  executable:
    inputs:
      path: /veld/input/
      content: csv
      description: "training data"
    outputs:
      path: /veld/output/
      content: word2vec model
      description: "NLP word2vec model"
    environment:
      TRAIN_DATA_FILE: "name of csv file used for training"
      MODEL_NAME: "arbitrary name of model, used for output files and logging"
          
services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src/train/:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root

