x-veld:
  executable:

services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root

