x-veld:
  executable:
    inputs:
      path: /veld/input/
      content: csv
      description: "uncleaned training data"
    outputs:
      path: /veld/output/
      content: csv
      description: "cleaned training data"
    environment:
      INPUT_FILE_NAME: "name of input file"
      OUTPUT_FILE_NAME: "name of output file"
          
services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src/clean/:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root



