x-veld:
  executable:

    inputs:
      description: "uncleaned or unprocessed training data"
      volume: /veld/input/
      type: "csv"
      content: 
        - "NLP training data"
        - "NLP data"

    outputs:
      description: "cleaned or processed training data"
      volume: /veld/output/
      type:
        - "csv"
        - "txt"
      content: 
        - "NLP training data"
        - "NLP data"

    environment:
      unprocessed_file_name:
        description: "path to unprocessed data file"
        type: string
        path_prefix: "/veld/input/"
      processed_file_name:
        description: "path to processed data file"
        type: string
        path_prefix: "/veld/output/"
          
services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./volumes/preprocess/input/:/veld/input/
      - ./volumes/preprocess/output/:/veld/output/
      - ./src/preprocess/:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
    environment:
      unprocessed_file_name: "/veld/input/<REPLACE>"
      processed_file_name: "/veld/output/<REPLACE>"

