x-veld:
  code:
    about:
      description:
      topics:

    inputs:
      volume: /veld/input/
      file_formats:
        - "csv"
        - "txt"
      contents: 
        - "NLP training data"
        - "NLP data"

    outputs:
      volume: /veld/output/
      file_formats: "word2vec model"
      contents:
        - "NLP model"
        - "word embeddings model"

    environment:
      # TODO: add epochs
      in_train_data_file:
        description: "path to training data file"
        type: path
        path_prefix: "/veld/input/"
      train_data_description:
        description: "short human description for the kind of training data"
        type: string
        optional: true
      out_model_file:
        description: "path to model file"
        type: path
        path_prefix: "/veld/output/"
      vector_size: 
        description: "word2vec hyperparameter"
        type: int
        default: 500
      window: 
        description: "word2vec hyperparameter"
        type: int
        default: 5
      min_count: 
        description: "word2vec hyperparameter"
        type: int
        default: 5
          
services:
  veld_train:
    build: .
    command: python /veld/code/train.py
    volumes:
      - ./volumes/train/input/:/veld/input/:z
      - ./volumes/train/output/:/veld/output/:z
      - ./src/train/:/veld/code/:z
    environment:
      in_train_data_file: null
      out_model_file: null
      model_description: null
      epochs: 100
      vector_size: 200
      window: 5
      min_count: 5

