x-veld:
  executable:
    inputs:
      -
        path: /veld/input/
        environment:
          INPUT_FILE_NAME: "name of input file"
    outputs:
      -
        path: /veld/output/
        environment:
          OUTPUT_FILE_NAME: "name of output file"
          
services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src/clean/:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root



