x-veld:
  executable:

    inputs:
      volume: /veld/input/
      type:
        - "csv"
      content: 
        - "NLP training data"
        - "NLP data"

    outputs:
      volume: /veld/output/
      type: "word2vec model"
      content:
        - "NLP model"
        - "word embeddings model"

    environment:
      train_data_path:
        description: "path to training data file"
        type: string
        prefix: "/veld/input/"
      train_data_description:
        description: "short human description for the kind of training data"
        type: string
      model_path:
        description: "path to model file"
        type: string
        prefix: "/veld/output/"
      model_architecture:
        description: "short label for the overall training setup"
        type: string
      model_id: 
        description: "id for the specific model"
        type: string
      vector_size: 
        description: "word2vec hyperparameter"
        type: int
      window: 
        description: "word2vec hyperparameter"
        type: int
      min_count: 
        description: "word2vec hyperparameter"
        type: int

    chain_template: # you can copy this template below into a new chain veld.yaml for using this executable
      x-veld:
        chain:
      services:
        veld:
          extends:
            file: ./<REPLACE_WITH_ROOT_FOLDER_OF_EXECUTABLE>/veld_train.yaml
            service: veld
          volumes:
            - ./<REPLACE_WITH_ROOT_FOLDER_OF_TRAINING_DATA>/:/veld/input/
            - ./<REPLACE_WITH_ROOT_FOLDER_OF_MODEL>/:/veld/output/
          environment:
            train_data_path: "/veld/input/<REPLACE_WITH_RELATIVE_PATH>"
            train_data_description: "<REPLACE_OR_NOT>" 
            model_path: "/veld/output/<REPLACE_WITH_RELATIVE_PATH>"
            model_architecture: "<REPLACE>"
            model_id: "<REPLACE>"
            vector_size: "<REPLACE>"
            window: "<REPLACE>"
            min_count: "<REPLACE>"
          
services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src/train/:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
    environment:
      workers: -1

