x-veld:
  code:
    about:
      description: "a fasttext training and inference jupyter notebook."
      topics:
        - "NLP"
        - "Machine Learning"
        - "word embeddings"

    storage:
      volume: /veld/storage/

services:
  veld_jupyter_notebook:
    build: .
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    volumes:
      - ./src/jupyter_notebook/:/veld/code/:z

