x-veld:
  code:
    # TODO
    about:
      description:
      topics:

    inputs:
      description: "uncleaned or unprocessed training data"
      volume: /veld/input/
      file_formats: "csv"
      contents: 
        - "NLP training data"
        - "NLP data"

    outputs:
      description: "cleaned or processed training data"
      volume: /veld/output/
      file_formats:
        - "csv"
        - "txt"
      contents: 
        - "NLP training data"
        - "NLP data"

    environment:
      unprocessed_file_name:
        description: "path to unprocessed data file"
        type: path
        path_prefix: "/veld/input/"
      processed_file_name:
        description: "path to processed data file"
        type: path
        path_prefix: "/veld/output/"
          
services:
  veld_preprocess:
    build: .
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
    ports:
      - 8888:8888
    volumes:
      - ./volumes/preprocess/input/:/veld/input/
      - ./volumes/preprocess/output/:/veld/output/
      - ./src/preprocess/:/veld/code/
    working_dir: /veld/code/
    environment:
      unprocessed_file_name: null
      processed_file_name: null

