x-veld:
  code:
    about:
      description: "a fasttext training and inference jupyter notebook."
      topics:
        - "NLP"
        - "Machine Learning"
        - "word embeddings"

    data:
      volume: /veld/data/

services:
  veld_jupyter_notebook:
    build: .
    #command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    command: python /veld/code/test.py
    #ports:
    #  - 8888:8888
    volumes:
      - ./src/jupyter_notebook/:/veld/code/:z

